import { ClerkProvider } from '@clerk/nextjs'
import AuthHeader from '@/components/AuthHeader';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className="antialiased">
        <AuthHeader />
        {children}
      </body>
    </html>
  </ClerkProvider>
  );
}
